export const list = [
  { id: "1", name: "IIT Kharagpur" },
  { id: "2", name: "IIT Bombay" },
  { id: "3", name: "IIT Madras" },
  { id: "4", name: "IIT Kanpur" },
  { id: "5", name: "IIT Delhi" },
  { id: "6", name: "IIT Guwahati" },
  { id: "7", name: "IIT Roorkee" },
  { id: "8", name: "IIT Ropar" },
  { id: "9", name: "IIT Bhubaneswar" },
  { id: "10", name: "IIT Gandhinagar" },
  { id: "11", name: "IIT Hyderabad" },
  { id: "12", name: "IIT Jodhpur" },
  { id: "13", name: "IIT Patna" },
  { id: "14", name: "IIT Indore" },
  { id: "15", name: "IIT Mandi" },
  { id: "16", name: "IIT (BHU) Varanasi" },
  { id: "17", name: "IIT Palakkad" },
  { id: "18", name: 'IIT Tirupa"ti' },
  { id: "19", name: "IIT (ISM) Dhanbad" },
  { id: "20", name: "IIT Bhilai" },
  { id: "21", name: "IIT Dharwad" },
  { id: "22", name: "IIT Jammu" },
  { id: "23", name: "IIT Goa" },
];
