export const list = [
  { id: "1", name: "IIT Kharagpur", link: "/IIT/1.png" },
  { id: "2", name: "IIT Bombay", link: "/IIT/2.png" },
  { id: "3", name: "IIT Madras", link: "/IIT/3.png" },
  { id: "4", name: "IIT Kanpur", link: "/IIT/4.png" },
  { id: "5", name: "IIT Delhi", link: "/IIT/5.png" },
  { id: "6", name: "IIT Guwahati", link: "/IIT/6.png" },
  { id: "7", name: "IIT Roorkee", link: "/IIT/7.png" },
  { id: "8", name: "IIT Ropar", link: "/IIT/8.png" },
  { id: "9", name: "IIT Bhubaneswar", link: "/IIT/9.png" },
  { id: "10", name: "IIT Gandhinagar", link: "/IIT/10.png" },
  { id: "11", name: "IIT Hyderabad", link: "/IIT/11.jpg" },
  { id: "12", name: "IIT Jodhpur", link: "/IIT/12.png" },
  { id: "13", name: "IIT Patna", link: "/IIT/13.png" },
  { id: "14", name: "IIT Indore", link: "/IIT/14.png" },
  { id: "15", name: "IIT Mandi", link: "/IIT/15.png" },
  { id: "16", name: "IIT (BHU) Varanasi", link: "/IIT/16.png" },
  { id: "17", name: "IIT Palakkad", link: "/IIT/17.png" },
  { id: "18", name: "IIT Tirupati", link: "/IIT/18.png" },
  { id: "19", name: "IIT (ISM) Dhanbad", link: "/IIT/19.png" },
  { id: "20", name: "IIT Bhilai", link: "/IIT/20.png" },
  { id: "21", name: "IIT Dharwad", link: "/IIT/21.png" },
  { id: "22", name: "IIT Jammu", link: "/IIT/22.png" },
  { id: "23", name: "IIT Goa", link: "/IIT/23.png" },
];
